<a href="https://colab.research.google.com/github/ubsuny/PHY386/blob/Homework2026/2026/HW/JoshProfeta/HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
def solve_bridge_circuit(V0, R1, R2, R3, R4, R5):
  """ Solve a bridge circuit with five resistors and one voltage source.

  The circuit has the topography:
      B ---/\/\/--- C--(-)
      |\    R4      |
      | \           |
      R3 \__R5 _    R2
      |         \   |
      |     R1   \  |
  (+)-A ---/\/\/--- D

  Uses Kirchhoff's Current and Voltage Laws to create
  a system of linear equations A*I = b.

  Parameters
  ----------
  V0: float
    Voltage of source between A and C (V)
  R1, R2, R3, R4: float
    Resistances of the bridge resistors (Ohms)
  R5: float
    Galvanometer (bridge resistor between B and D) resistance (Ohms)

  Returns
  -------
  Currents : numpy.ndarray
    Array [I1 I2 I3 I4 I5] of branch currents (A).
  """
  # Assume current directions:
  # I1: V0 -> R1 -> Node D
  # I2: Node D -> R2 -> Node C
  # I3: V0 -> R3 -> Node B
  # I4: Node B -> R4 -> Node C
  # I5: Node B -> R5 -> Node D

  # Formulate equations based on KCL at nodes B and D, and KVL for three separate loops.
  # Equations:
  # 1. KCL at Node B: I3 - I4 - I5 = 0
  # 2. KCL at Node D: I1 + I5 - I2 = 0
  # 3. KVL Loop V0-R1-R2-C-V0: V0 - I1*R1 - I2*R2 = 0 => V0 = I1*R1 + I2*R2
  # 4. KVL Loop V0-R3-R4-C-V0: V0 - I3*R3 - I4*R4 = 0 +> V0 = I3*R3 + I4*R4
  # 5. KVL Loop D-R5-B-R4-R2-D: I5*R5 + I4*R4 - I2*R2 = 0

  import numpy as np
  A = np.array([
      [0, 0, 1, -1, -1],
      [1, -1, 0, 0, 1],
      [R1, R2, 0, 0, 0],
      [0, 0, R3, R4, 0],
      [0, -R2, 0, R4, R5]
  ], dtype=float)

  b = np.array([0, 0, V0, V0, 0], dtype=float)

  print("Matrix A")
  print(A)
  print("Vector b")
  print(b)

  currents = np.linalg.solve(A, b)
  return currents

# Given Values
V0 = 10 # Volts
R1 = 100 # Ohms
R2 = 200 # Ohms
R3 = 300 # Ohms
R4 = 600 # Ohms
R5 = 50 # Ohms

currents = solve_bridge_circuit(V0, R1, R2, R3, R4, R5)

print("Branch Currents:")
print(f"I1 = {currents[0]:.4f} A (through R1)")
print(f"I2 = {currents[1]:.4f} A (through R2)")
print(f"I3 = {currents[2]:.4f} A (through R3)")
print(f"I4 = {currents[3]:.4f} A (through R4)")
print(f"I5 = {currents[4]:.4f} A (through R5)")


Matrix A
[[   0.    0.    1.   -1.   -1.]
 [   1.   -1.    0.    0.    1.]
 [ 100.  200.    0.    0.    0.]
 [   0.    0.  300.  600.    0.]
 [   0. -200.    0.  600.   50.]]
Vector b
[ 0.  0. 10. 10.  0.]
Branch Currents:
I1 = 0.0333 A (through R1)
I2 = 0.0333 A (through R2)
I3 = 0.0111 A (through R3)
I4 = 0.0111 A (through R4)
I5 = -0.0000 A (through R5)


<>:5: SyntaxWarning: invalid escape sequence '\/'
<>:5: SyntaxWarning: invalid escape sequence '\/'
/tmp/ipython-input-226/1108803530.py:5: SyntaxWarning: invalid escape sequence '\/'
  B ---/\/\/--- C--(-)


### Part 1: Bridge Circuit (32 points)

A bridge is a classic circuit used to measure unknown resistances with high precision.

```
     B ---/\/\/--- C--(-)
     |\     R₄     |
     | \           |
     R₃ \__R₅ __   R₂
     |          \  |
     |      R₁   \ |         
(+)--A ---/\/\/--- D

```

- $V_0$: voltage source between A and C
- $R_1, R_2, R_3, R_4$: bridge resistors
- $R_5$: galvanometer (bridge resistor between B and D)

#### Tasks:

1. **Set up the equations** (10 points)  
   Write a function `build_system(V0, R1, R2, R3, R4, R5)` that returns the coefficient matrix $A$ and the right-hand-side vector $\vec{b}$ for the bridge circuit using Kirchhoff's laws. Your function should return both `A` and `b`.

2. **Solve and verify** (10 points)  
   Write a function `solve_circuit(A, b)` that solves the system and returns all branch currents. Test it with $V_0 = 10$ V, $R_1 = 100 \ \Omega$, $R_2 = 200 \ \Omega$, $R_3 = 300 \ \Omega$, $R_4 = 600 \ \Omega$, $R_5 = 50 \ \Omega$.  
   Verify your result using a power balance check.

3. **Balanced bridge condition** (12 points)  
   A circuit bridge is *balanced* when no current flows through $R_5$ (the galvanometer), which happens when:
   $$\frac{R_1}{R_3} = \frac{R_2}{R_4}$$
   - Write a function that takes the four bridge resistors and checks whether the bridge is balanced.  